version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: b4n4d
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker login --username b4n4d --password $DOCKERHUB_PASSWORD
          docker build -tag b4n4d/dockertest:$TAG .
          docker push b4n4d/dockertest:$TAG
