version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKERHUB_USERNAME/dockertest:$TAG .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker push $DOCKERHUB_USERNAME/dockertest:$TAG
